window:
  width: 960
  height: 540
time:
  tick_rate_hz: 30
  minutes_per_tick: 0.2
  day_length_minutes: 1440
random_seed: 1337
movement:
  pc_speed_tiles_per_sec: 3.0
  npc_speed_tiles_per_sec: 2.5
map:
  tile_size: 32
data:
  map_file: data/campus_map_v1.json
  npc_schedule_file: config/schedules/npc_assignments.yaml
interactions:
  messages_file: config/interactions.yaml
