rooms:
  ClassroomA:
    room_type: "classroom"
    x: 50
    y: 50
    width: 200
    height: 120

  Cafeteria:
    room_type: "cafeteria"
    x: 300
    y: 50
    width: 200
    height: 120

  DormA:
    room_type: "dorm"
    x: 50
    y: 200
    width: 200
    height: 120

  Lounge:
    room_type: "lounge"
    x: 300
    y: 200
    width: 200
    height: 120

  BathroomA:
    room_type: "bathroom"
    x: 550
    y: 50
    width: 100
    height: 80
