# configs/uniforms.yaml

student:
  clothing:
    upper:
      categories:
        - name: default
          items: ["White blouse", "Light-blue blouse"]
        - name: warm
          items: ["Short-sleeve white polo", "Short-sleeve light-blue blouse"]
        - name: cold
          items: ["Long-sleeve white blouse", "Long-sleeve light-blue blouse"]
    upper_under:
      categories:
        - name: default
          items: ["White camisole"]
        - name: warm
          items: ["Nude tank top"]
        - name: cold
          items: ["Thermal undershirt"]
    lower:
      categories:
        - name: default
          items: ["Navy skirt"]
        - name: warm
          items: ["Navy shorts"]
        - name: cold
          items: ["Navy wool skirt"]
    lower_under:
      categories:
        - name: default
          items: ["White ankle socks"]
        - name: warm
          items: ["Navy bike shorts"]
        - name: cold
          items: ["Black tights"]
    socks:
      categories:
        - name: default
          items: ["White crew socks"]
        - name: cold
          items: ["Navy knee-high socks"]
    shoes:
      categories:
        - name: default
          items: ["Black Mary Janes", "Black loafers"]

  accessories:
    neck:
      categories:
        - name: default
          items: ["Blue ribbon", "School tie"]
        - name: cold
          items: ["Knit scarf"]
    wrists:
      categories:
        - name: default
          items: ["Watch", "Friendship bracelet"]
    ankles:
      categories:
        - name: default
          items: ["Ankle bracelet"]
    ears:
      categories:
        - name: default
          items: ["Stud earrings", "Hoop earrings"]
    head:
      categories:
        - name: default
          items: ["Headband", "Hair clip"]
    back:
      categories:
        - name: default
          items: ["School backpack", "Messenger bag"]

staff:
  clothing:
    upper:
      categories:
        - name: default
          items: ["White blouse", "Light-blue button-up"]
        - name: cold
          items: ["Blazer"]
    upper_under:
      categories:
        - name: default
          items: ["Tank top"]
        - name: cold
          items: ["Thermal undershirt"]
    lower:
      categories:
        - name: default
          items: ["Black slacks", "Gray skirt"]
    lower_under:
      categories:
        - name: default
          items: ["Black hosiery"]
    socks:
      categories:
        - name: default
          items: ["Black dress socks"]
    shoes:
      categories:
        - name: default
          items: ["Black dress shoes", "Black flats"]

  accessories:
    neck:
      categories:
        - name: default
          items: ["Neck scarf", "Tie"]
    wrists:
      categories:
        - name: default
          items: ["Watch"]
    ears:
      categories:
        - name: default
          items: ["Stud earrings"]
    back:
      categories:
        - name: default
          items: ["Briefcase", "Tote bag"]
